/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <termios.h>
/* Header for class JniTest_FFmpegCmd */

#ifndef _Included_FFmpeg_Cmd
#define _Included_FFmpeg_Cmd
//#ifdef __cplusplus
//extern "C" {
//#endif
//#ifdef __cplusplus
//}
//#endif
#endif

void ffmpeg_progress(float progress);
void ffmpeg_complete(int errorCode);
int donwloadFile(const char* input, const char* output);

//全局静态变量 .
static pthread_t pid_dump; //the thread id .use to interrupt the download thread .
static const char * inputPath; //input stream address .
static const char * outputPath; // the output file absolute path .
/**
 * 1： dump file is doing .
 * 0: stop dump and ready to exit .
 */
static int isDownloading ;